# -*- coding: utf-8 -*-
"""cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yncSNnx6MzU99aYyWeXOQ2Q7xZgXBjdF

# Librerías
"""

install.packages('dendextend')

install.packages('StatMatch')

install.packages('factoextra')

install.packages('vegan')

library(cluster)
library(purrr)
library(factoextra)
library(StatMatch)
library(vegan)
library(dendextend)

"""# Ejercios de clase

## 1

Se escalan los datos de las variables numéricas, esto significa que cada variable ahora tendrá una media cero y una desviación estándar uno. Lo ideal es que quieras que cada variable tenga la misma unidad de escala, de modo que una unidad en cada coordenada represente la misma magnitud de diferencia. Escalar evita que el algoritmo de agrupamiento dependa de una unidad arbitraria. Puedes escalar los datos usando la función `scale():
"""

# Base de datos
datos <- carData::Freedman

# Se eliminan los valores perdidos de los datos
datos <- na.omit(datos)

# Se escalan los datos de las variables numéricas, esto
# significa que cada variable ahora tendrá una media cero
# y una desviación estándar uno.
# Lo ideal es que quieras que cada variable tenga la misma unidad de escala,
# de modo que una unidad en cada coordenada represente la misma magnitud de diferencia.
# Escalar evita que el algoritmo de agrupamiento dependa de una unidad arbitraria.
# Puedes escalar los datos usando la función scale():
# ---------------------------------------------------------
datos <- scale(datos)

"""## Medidas de similitud: distancias comandos: `dist()` y `get_dist()

Calculando las distancias con el método seleccionado. Por default, se usa la distancia euclidiana.
"""

# Distancia Euclidiana
d1 <- dist(datos, method = "euclidean")

# Redondear la matriz de distancias (primeras 4 filas y columnas)
round(as.matrix(d1)[1:4, 1:4], 2)

# Visualizar la matriz completa en una ventana aparte
View(round(as.matrix(d1)[1:4, 1:4], 2))

# Distancia de tipo "máximo" (Chebyshev)
d2 <- dist(datos, method = "maximum")
round(as.matrix(d2)[1:4, 1:4], 2)


d3 <- dist(datos, method = "manhattan")
round(as.matrix(d3)[1:4, 1:4], 2)

d4 <- dist(datos, method = "canberra")
round(as.matrix(d4)[1:4, 1:4], 2)

d5 <- dist(datos, method = "minkowski",p=4)
round(as.matrix(d5)[1:4, 1:4], 2)

# Cálculo de la distancia de Mahalanobis
d6 <- mahalanobis.dist(data.x = datos)

# Convertir el resultado a objeto tipo "dist"
d6 <- as.dist(d6)

# Mostrar las primeras 4 filas y columnas redondeadas
round(as.matrix(d6)[1:4, 1:4], 2)

"""La distancia de Mahalabous no necesita que se escalen los datos, ya que da el mismo resultado, en cambio las otras distancias si cambian su resultado"""

datos.2 <- carData::Freedman
datos.2 <- na.omit(datos.2)

d6.a <- mahalanobis.dist(data.x=datos.2)
d6.a <- as.dist(d6.a)
round(as.matrix(d6.a)[1:4,1:4],2)

"""## Coeficiente de correlación

Para usar la funcion `get_dist` que acepta además de los anteriores, las diferencias basadas en correlación
"""

# Correlación de Pearson
d7 <- get_dist(x = datos, method = "pearson")
round(as.matrix(d7)[1:4,1:4],2)

"""## Coeficinete de asociación"""

d8 <- vegdist(datos,mehod="jeccard")
round(as.matrix(d8)[1:4,1:4],2)

"""Realizando los mapas de calos (`heatmap`) de las matrices de distancia obtenidas anteriormente"""

fviz_dist(d1,show_labels=F)
fviz_dist(d2)
fviz_dist(d3)
fviz_dist(d4)
fviz_dist(d5)
fviz_dist(d6)
fviz_dist(d7)
fviz_dist(d8)

"""## Agrupamiento Jerarquico aglomerativo

Se usa el comando `hclust()` requiere la matriz de distancia
"""

# Enlace simple o método del vecino más cercano
h1.s <- hclust(d1,method = "single")
plot(h1.s,cex=0.6,hang=-1)
abline(h=4.5,lty=2)

# Enlace completo o método del vecino más lejano
h1.c <- hclust(d1)
plot(h1.c,cex=0.6,hang=-1)
abline(h=4.5,lty=2)

# Unión mediante el promedio
h1.a <- hclust(d1, method = "average")
plot(h1.a,cex=0.6,hang=-1)
abline(h=4.5,lty=2)

# Como cambian los closters si cambiamos a d2
h1.b <- hclust(d2,method = "average")
plot(h1.b,cex=0.4,hang=-1)
abline(h=0.8,lty=2)

# Método de ward
h1.w <- hclust(d1, method = "ward.D")
plot(h1.w,cex=0.5,hang=-1)
abline(h=4.5,lty=2)

"""Otra alternativca es la función agnes. Ambas funciones son bastante similares; sin embargo, con la funciópn `agnes()` tambien se puede obtener el coeficiente de agloimeracion, que mide la cantidad de estructura de agrupamiento encontrada (los valores mpas cercanos a 1 suguieren una estructura de agrupacion fuerte)"""

a1 <- agnes(d1, method = "complete")
# Coeficiente de aglomeración
a1$ac

"""Vamos a comparar los métodos ya mencionados

"""

m <- c("average", "single", "complete", "ward")

names(m) <- c("average", "single", "complete", "ward")

m

# Función para calcular los ceoficientes

ac <- function(x){
  agnes(d1,method = x)$ac
}

"""Se evalúa la fuinción anterior en los valores ya definidos en `m` y se observa que el coeficiente más alto es el que corresponde a el método `ward`"""

map_dbl(m,ac)

# VEamos el dendograma correpsondinete a este método:

a1.w <- agnes(d1, method = "ward")
pltree(a1.w,cex=0.4,hang=-1,main="Dendograma de agnes")
abline(h=4.5,lty=2)

"""## Agrupamiento divisional jerárquico

La función `diana` enel paquete cluster nos ayuda a realizar agrupamientos jerárquicos divisivos, `diana` funciona de manera similar que `agnes`. No hay un argumento de método aquí, y, en lugar de coeficiente de aglomeración, tenemos un _coeficiente de división_
"""

d.d1 <- diana(d1)
# Coeficiente de división
d.d1$dc

"""Graficamos los resultados obtenidos con la función `diana`"""

pltree(d.d1,cex=0.6,hang=-1,main="Dendograma de DIANA")
abline(h=4.5,lty=2)

"""Se pueden administrar dendotgramas y ahcer mucho más con ellos usando el paquete `dendextend`

Vamos a asignar clusters a los puntos de los datos. Esto se puede hacer con la función `R cutree`. Corta un árbol (o dendograma), como resultado de  `hclust` (o diana / agnes), en varios grupos, ya sea especificando el número deseado de grupós $k$ o la altura de corte $h$. Se debe especificar al menos uno de $k$ o $h$, $k$ anula $h$ si se dan ambos.

"""

clust <- cutree(d.d1,k=5)
clust

"""Graficamos el resultado, para mostras los clusteers obtenidos"""

fviz_cluster(list(data=datos,cluster= clust))

"""También se pueden visualizar lso clusters dentro del dendograma colocando brodes comos e muestra a continuación"""

# Aqui se eligieron 5 conglomerados
pltree(d.d1,hang=-1,cex=0.6)
rect.hclust(d.d1,k=5,border=2:10)

"""El tanglegrama se usa para comparar dos sdendogramas (con el mismo conjunto de etiquetas), uno frente al otro y con sus etiquetas conectadas por lineas.

Como ejemplo, comparemos los métodos de valoración simple y completo para la función de `agnes`.
"""

hc_single <- agnes(datos,method="single")
hc_complete <- agnes(datos,method="complete")

"""Se convierten a objetos tipo dendogramas, ya que `dendextend` trabaja con ese tipo de variables"""

hc_single <- as.dendrogram(hc_single)
hc_complete <- as.dendrogram(hc_complete)

tanglegram(hc_single,hc_complete,columns_width= c(1,1,1),cex_main=0.5,hang=1.5)

plot(hc_single,type="triangle")

"""## Ejemplo con delitos

Leemos los datos que vamos a usar
"""

data("USArrests")
# Estandarizamos los datos
df <- scale(USArrests)

"""Observamos las primeras filas"""

head(df,nrow=6)

"""Observamos la erstructura de los datos"""

str(df)
summary(df)

"""Se ecala la matriz de distancias: Matriz de similitud y disimilitud"""

res.dist <- dist(df,method = "euclidean")
round(as.matrix(res.dist)[1:6,1:6],2)

"""Linkage (Vinculación = Enlace)"""

res.hc <- hclust(d=res.dist,method = "ward.D2")
res.hc

"""Dendograma"""

fviz_dend(res.hc,cex=0.5)

clust <- cutree(res.hc,k=5) # La k represetna el numero de clusters que deseamos,
# tambien podemos especificar con h la altura a la que queremos que se deifnian los clusters
clust

"""Graficamos el resultado para mostrar los clusters obtenidos"""

fviz_cluster(list(data=df,cluster=clust))

"""### Verificación del arbol

Una forma de medir que tan bien refleja el arbol de conglomerados (cluster), generado por la funcoin `hclust` es calculando al correlacion entre la distancia confenetica y los datos de distancia originales,  generados por la función `dist`. Si la agrupación es válida, la vinculación de obhjetivos en un árbol de conglomerados debe tener una fuerte correlación coin las distancias entre objetos de la matriz de distancia original.

La distancia confenetica entre dos objetos en un dendograma es la distancia entre los dos objetos se convierten en miembros del mismo grupo
"""

# Calculando al distancia cophenetic
res.coph <- cophenetic(res.hc)

"""El método con al correlación confenética más alta puede verse como el que produce el modelo de agrupación que retiene la mayor parte de la información contenida en al matriz de similitud. Sin embargo, esto no significa necesariamente que este modelo de agrupamiento dea el más adecuado apra el objetivo del investigador.


"""

# Correlación entre la distancia copgenetic y la distancia original
cor(res.dist,res.coph)

# Cambiamos el método en hclust
res.hc2 <- hclust(res.dist,method = "average")

# Calculamos la correlación
cor(res.dist,cophenetic(res.hc2))

"""El coeficiente de correlaciuón muestra que usando diferentes métodos de vinculación (linkcage) se crea un árbol que representa als distancais originales ligeramente mejor

### Cortando el dendrograma para crear los grupos
"""

# Cortando el árbol en 4 grupos
grp <- cutree(res.hc,k=4)
head(grp,n=4)

# Número de miembros por cluster
table(grp)

# Obteniendo los nombres de los miembros de el clúster
rownames(df)[grp==1]

"""### Visualización del agrupamiento"""

# Cortando en 4 grupos y coloreandolos
fviz_dend(res.hc,k=4,
          cex=0.5,
          k_colors = c("red","yellow3","blue","green4"),
          color_labels_by_k=TRUE,
          rect=TRUE
          )

"""## Libreria cluster"""

# AGlomerative NESting (Hierarachical CLustering)
res.agnes <- agnes(x=USArrests,
                   stand=TRUE,
                   metric="euclidean",
                   method="ward"
                  )

# DIvisive ANAlysis Clustering
res.diana <- diana(x=USArrests,
                   stand=TRUE,
                   metric="euclidean")

"""Se visualizan los resultados con cada uno de los métodos"""

fviz_dend(res.agnes,cex=0.6,k=4,palette="rickandmorty")
fviz_dend(res.diana,cex=0.6,k=4)